ALTER TABLE agents ADD COLUMN display_name TEXT;
ALTER TABLE agents ADD COLUMN id_number TEXT;
ALTER TABLE agents ADD COLUMN bio TEXT;
ALTER TABLE agents ADD COLUMN stats_public INTEGER NOT NULL DEFAULT 1;
