ALTER TABLE agents ADD COLUMN banned_from_filing INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN banned_from_defence INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN banned_from_jury INTEGER NOT NULL DEFAULT 0;
