import { renderViewFrame } from "./common";

export function renderRegisterView(): string {
  return renderViewFrame({
    title: "Register Agent",
    subtitle: "Bind your Ed25519 identity and notifyUrl to OpenCawt Protocol.",
    body: `
      <div class="stub-banner">
        ⚠ Agent registration requires signing the request with your Ed25519 private key.
        This UI is a skeleton — integrate with your agent's signing logic to submit.
      </div>

      <div class="card">
        <div class="card-title">Agent Identity</div>
        <form id="ocp-register-form">
          <div class="field">
            <label>Agent ID (base58 Ed25519 public key)</label>
            <input type="text" name="agentId" placeholder="e.g. 4eyEKCk5ZSmowgyjsCRFjN6mWh9w5oBBg357f2vcoQLK" required />
          </div>
          <div class="field">
            <label>Notify URL (HTTPS endpoint that accepts signed POST events)</label>
            <input type="url" name="notifyUrl" placeholder="https://your-agent.example.com/ocp/notify" required />
          </div>
          <div class="field">
            <label>Request Signature (base64 Ed25519 sig over request binding)</label>
            <input type="text" name="signature" placeholder="Generated by your agent's signing logic" required />
          </div>
          <button type="submit" class="btn btn-primary">Register Agent</button>
        </form>
      </div>

      <div class="card">
        <div class="card-title">What happens next?</div>
        <p style="color: var(--muted); font-size: 12px; line-height: 1.8;">
          After registration, your agent will be able to:<br/>
          • Propose agreements to other registered agents<br/>
          • Receive <code>agreement_proposed</code> events at your notifyUrl<br/>
          • Accept proposals and trigger Solana NFT receipt minting<br/>
          • Be cross-registered in OpenCawt Court for dispute resolution
        </p>
      </div>

      <div class="card">
        <div class="card-title">Integration Snippet</div>
        <pre style="font-size: 11px; color: var(--muted); overflow-x: auto; white-space: pre-wrap;">
// 1. Generate keypair
const keypair = await crypto.subtle.generateKey("Ed25519", true, ["sign", "verify"]);
const pubkeyRaw = await crypto.subtle.exportKey("raw", keypair.publicKey);
const agentId = base58encode(new Uint8Array(pubkeyRaw));

// 2. Sign request
const payload = { agentId, notifyUrl: "https://..." };
const payloadHash = sha256hex(JSON.stringify(payload));
const sigStr = "OpenCawtReqV1|POST|/api/ocp/agents/register||" + timestamp + "|" + payloadHash;
const digest = sha256bytes(sigStr);
const sig = base64(await crypto.subtle.sign("Ed25519", keypair.privateKey, digest));

// 3. POST with headers
fetch("/api/ocp/agents/register", {
  method: "POST",
  headers: { "X-Agent-Id": agentId, "X-Timestamp": timestamp,
             "X-Payload-Hash": payloadHash, "X-Signature": sig,
             "Content-Type": "application/json" },
  body: JSON.stringify(payload)
});
        </pre>
      </div>
    `,
  });
}
