import { renderLinkButton } from "../components/button";
import { renderEvidenceCard } from "../components/evidenceCard";
import { renderJurorGrid, type JurorDetail } from "../components/jurorGrid";
import { renderStatusPill, statusFromOutcome } from "../components/statusPill";
import type { Case, Decision, PartySubmissionPack, TranscriptEvent } from "../data/types";
import { titleCaseOutcome } from "../util/format";
import { escapeHtml } from "../util/html";
import { renderViewFrame } from "./common";
import { renderTranscript } from "./caseDetailView";

function renderPrinciples(principles: Array<number | string>): string {
  return `<div class="principle-tags">${principles
    .map((principle) => {
      const label =
        typeof principle === "number"
          ? `P${principle}`
          : /^P/i.test(principle.trim())
            ? principle.trim().toUpperCase()
            : `P${principle.trim()}`;
      return `<span class="principle-tag">${escapeHtml(label)}</span>`;
    })
    .join("")}</div>`;
}

function renderPartyColumn(label: string, pack: PartySubmissionPack): string {
  return `
    <article class="party-column glass-overlay">
      <h3>${escapeHtml(label)}</h3>
      <div class="content-block-card">
        <h4>Opening addresses</h4>
        <p>${escapeHtml(pack.openingAddress.text)}</p>
      </div>
      <div class="content-block-card">
        <h4>Evidence</h4>
        <div class="evidence-grid">
          ${pack.evidence.map((item) => renderEvidenceCard(item)).join("")}
        </div>
      </div>
      <div class="content-block-card">
        <h4>Closing addresses</h4>
        <p>${escapeHtml(pack.closingAddress.text)}</p>
      </div>
      <div class="content-block-card">
        <h4>Summing up</h4>
        <p>${escapeHtml(pack.summingUp.text)}</p>
        ${renderPrinciples(pack.summingUp.principleCitations)}
      </div>
    </article>
  `;
}

function getMockJurorDetails(size: number, tally: { forProsecution: number; forDefence: number; insufficient: number }): JurorDetail[] {
  const details: JurorDetail[] = [];
  let p = tally.forProsecution;
  // We can also use insufficient counts, but let's assume they map to Nay or just fill the rest
  
  for (let i = 0; i < size; i++) {
    let vote: "yay" | "nay";
    if (p > 0) {
      vote = "yay";
      p--;
    } else {
      vote = "nay";
      // d-- or just consume rest
    }
    
    details.push({
      index: i,
      status: "cast",
      vote,
      rationale: vote === "yay" 
        ? "The evidence presented clearly links the defendant to the claim. The on-chain records match the timeline provided by the prosecution."
        : "The prosecution failed to provide sufficient evidence of intent. The logs are ambiguous and could have been generated by a third party.",
      principles: vote === "yay" ? ["P2 Evidence", "P8 Integrity"] : ["P5 Minimisation", "P9 Fair Process"]
    });
  }
  return details;
}

export function renderDecisionDetailView(
  decision: Decision,
  caseItem?: Case | null,
  transcript?: TranscriptEvent[]
): string {
  const txLink =
    decision.sealInfo.txSig && decision.sealInfo.txSig !== "pending"
      ? `https://solscan.io/tx/${encodeURIComponent(decision.sealInfo.txSig)}`
      : "";
  const assetLink =
    decision.sealInfo.assetId && decision.sealInfo.assetId !== "pending"
      ? `https://solscan.io/account/${encodeURIComponent(decision.sealInfo.assetId)}`
      : "";

  const decisionHeader = `
    <section class="case-header-card">
      <div class="stack">
        <div class="case-idline">
          <span class="case-id">${escapeHtml(decision.caseId)}</span>
          ${renderStatusPill(titleCaseOutcome(decision.outcome), statusFromOutcome(decision.outcome))}
        </div>
        <p>${escapeHtml(decision.summary)}</p>
        <div>
          <h4>Verdict summary</h4>
          <p>${escapeHtml(decision.verdictSummary)}</p>
        </div>
      </div>
    </section>
  `;

  const leftPanel = `
    <div class="panel-container">
      <div class="panel-header">Parties</div>
      <div class="panel-body">
        <div class="stack">
          ${caseItem ? `
            ${renderPartyColumn("Prosecution", caseItem.parties.prosecution)}
            ${renderPartyColumn("Defence", caseItem.parties.defence)}
          ` : `
            <p class="muted">Full case details archived.</p>
          `}
        </div>
      </div>
    </div>
  `;

  const middlePanel = `
    <div class="panel-container">
      <div class="panel-header">Court Transcript</div>
      <div class="panel-body">
         ${renderTranscript(transcript || [])}
      </div>
    </div>
  `;

  const primaryClaim = decision.claimTallies?.[0];
  const effectiveTally = primaryClaim
    ? {
        forProsecution: primaryClaim.proven,
        forDefence: primaryClaim.notProven,
        insufficient: primaryClaim.insufficient
      }
    : decision.voteSummary.tally;

  const rightPanel = `
    <div class="panel-container">
      <div class="panel-header">Jury Panel</div>
      <div class="panel-body">
        <div class="stack">
          ${renderJurorGrid({
            caseId: decision.caseId,
            jurySize: decision.voteSummary.jurySize,
            votesCast: decision.voteSummary.votesCast,
            jurorDetails: getMockJurorDetails(decision.voteSummary.jurySize, effectiveTally),
            completedTally: {
              proven: effectiveTally.forProsecution,
              notProven: effectiveTally.forDefence,
              insufficient: effectiveTally.insufficient,
            },
          })}

          <article class="record-card glass-overlay">
            <h3>Selected evidence</h3>
            <div class="evidence-grid">
              ${decision.selectedEvidence.map((item) => renderEvidenceCard(item)).join("")}
            </div>
          </article>

          <article class="record-card glass-overlay">
            <h3>Sealing details</h3>
            <dl class="key-value-list">
              <div>
                <dt>Asset ID</dt>
                <dd>${assetLink ? `<a href="${assetLink}" target="_blank" rel="noopener noreferrer">${escapeHtml(decision.sealInfo.assetId)}</a>` : escapeHtml(decision.sealInfo.assetId)}</dd>
              </div>
              <div>
                <dt>Tx sig</dt>
                <dd>${txLink ? `<a href="${txLink}" target="_blank" rel="noopener noreferrer">${escapeHtml(decision.sealInfo.txSig)}</a>` : escapeHtml(decision.sealInfo.txSig)}</dd>
              </div>
              <div>
                <dt>Verdict hash</dt>
                <dd>${escapeHtml(decision.sealInfo.verdictHash)}</dd>
              </div>
              <div>
                <dt>URI</dt>
                <dd>${escapeHtml(decision.sealInfo.sealedUri)}</dd>
              </div>
              <div>
                <dt>Seal status</dt>
                <dd>${escapeHtml(decision.sealStatus ?? decision.sealInfo.sealStatus ?? "pending")}</dd>
              </div>
            </dl>
          </article>
        </div>
      </div>
    </div>
  `;

  const body = `
    <div class="navigation-row">
      ${renderLinkButton("← Back to Past Decisions", "/past-decisions", "ghost")}
    </div>
    ${decisionHeader}
    <div class="case-view-layout">
      <div class="case-panel-col">
        ${leftPanel}
      </div>
      <div class="case-panel-col">
        ${middlePanel}
      </div>
      <div class="case-panel-col">
        ${rightPanel}
      </div>
    </div>
  `;

  return renderViewFrame({
    title: "Decision Detail",
    subtitle: "Recorded verdict summary with sealed receipt hashes and on-chain verification artefacts.",
    ornament: "Public Record",
    body,
    className: "case-layout"
  });
}

export function renderMissingDecisionView(): string {
  return renderViewFrame({
    title: "Decision not found",
    subtitle: "The requested decision identifier was not found in this dataset.",
    ornament: "Unavailable",
    body: `<div class="stack">${renderLinkButton("Return to Past Decisions", "/past-decisions", "pill-primary")}</div>`
  });
}
